### ISSUE TITLE
make human-friendly names for logs

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ChatAdditions/ChatAdditions_AMXX#119]
not the "*L%Y%m%d*"

example: "GAG_%Y-%m-%d"

**Comment by wopox1337** [comment]
Not agree with you. `L%Y%m%d` better for sorting and its default AMXX logs format

**Comment by Nord1cWarr1or** [comment]
@wopox1337 I don't like default logs format. And in my example format is the same: %y %m %d, then sorting will not change. Just make the date format more readable by using delimiters
