### ISSUE TITLE
cvar for my own reason for gag

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ChatAdditions/ChatAdditions_AMXX#133]
need to make cvar, who can access to write his own reason to gag

**Comment by wopox1337** [comment]
ca_gag_access_high? Already existed

**Comment by Nord1cWarr1or** [comment]
@wopox1337 no. It should be a individual cvars. **ca_gag_access_high**  means only that users with this flag have access to gag all other users, including users with immunity. 

need Something like **ca_gag_access_own_reason** and **ca_gag_access_own_time** for time.
