### ISSUE TITLE
adminchat support

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ChatAdditions/ChatAdditions_AMXX#134]
gagged by head admin users, can use adminchat for messaging. it's not good.
 amx_csay, amx_tsay, etc

**Comment by wopox1337** [comment]
@Nord1cWarr1or If you don't need this behavior - just place adminchat below CA_GAG plugin

**Comment by Nord1cWarr1or** [comment]
@wopox1337 I I'll test it

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or If you don't need this behavior - just place adminchat below CA_GAG plugin

dont work

**Comment by Nord1cWarr1or** [comment]
how is it supposed to work at all when the plugin doesn't hook these commands?
