### ISSUE TITLE
make new path for configs

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ChatAdditions/ChatAdditions_AMXX#139]
"configs/plugins" -> "configs/plugins/ChatAdditions"

There are already too many CA configurations. They get lost among the configs from the other plugins.

**Comment by afwn90cj93201nixr2e1re** [comment]
Please never use the paths that r used in the amxmodx core, use a different path like `'configs/CustomPluginsConfigs/ChatAdditions'` etc.
