### ISSUE TITLE
Blanks can only be added after items.

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ChatAdditions/ChatAdditions_AMXX#152]
```
L 03/18/2021 - 21:15:10: Blanks can only be added after items.
L 03/18/2021 - 21:15:10: [AMXX] Displaying debug trace (plugin "CA_Gag.amxx", version "0d203fd")
L 03/18/2021 - 21:15:10: [AMXX] Run time error 10: native error (native "menu_addtext")
L 03/18/2021 - 21:15:10: [AMXX]    [0] CA_Gag.sma::MenuShow_SelectReason (line 389)
L 03/18/2021 - 21:15:10: [AMXX]    [1] CA_Gag.sma::MenuHandler_PlayersList (line 339)
```
How to reproduce: remove all templates from **ca_gag_reasons.cfg** and try to gag someone without admin flag whitch is set in cvar **ca_gag_access_flags_own_reason**.

my suggestions for a solution:

1. In the case of such a situation, make the addition of a single menu item, which can be called, for example, "Not specified" (Не указана). 

2. Or just don't show gag menu to player without own reason access, and print him in chat something like: "reasons do not set and u don't have access to set your own reason"

**Comment by wopox1337** [comment]
Fixed in #153
