### ISSUE TITLE
problems with cmdaccess.ini

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ChatAdditions/ChatAdditions_AMXX#159]
Сейчас имеется проблема с командами плагина и **cmdaccess.ini**. Суть: при изменении в плагинах флага доступа к командам, в **cmdaccess.ini** остаётся старый флаг доступа, приходится делать всё руками. 

Вытекающие проблемы:

1. У целевой аудитории - серверодержателей с 99% вероятностью стояли раньше плагины гага, соответственно они уже оставили свои флаги доступа к командам, которые зачастую совпадают с командами СА. Предвижу кучи вопросов в духе "а почему у меня обычные админы могут использовать amx_gag" и всё в таком духе.

2. Обновления СА. Например, в одном из недавних обновлений я добавил функционал, позволяющий назначить отдельный флаг для ввода своей причины и времени. В итоге, даже если СА был установлен на сервер с нуля, в файле осталось предыдущее значение флага. То же самое касается грядущих обновлений.

Возможные пути решения: 

А) Уйти от проверок по типу cmd_access(), к простым проверкам на флаг. 
Б) В ридми тупо написать о необходимости удаления или правки руками при переходе с другого плагина на этот, и при обновлении. Но это далеко не лучшее решение, dont you? если делать - то делать нормально.
В) Если есть способ - изменять/обновлять cmdaccess через сам плагин.

**Comment by wopox1337** [comment]
Можно просто отказаться от флаг-менеджера, передав параметры в функции регистрации команд. 

https://github.com/alliedmodders/amxmodx/blob/70d1aff5190dff04e9b9ce9eaa0a96d4af5c48a0/plugins/include/amxmodx.inc#L1889-L1890
