### ISSUE TITLE
OnConfigsExecuted не всегда работает

### ISSUE THREAD

**Issue by 2020karaulov2020** [ChatAdditions/ChatAdditions_AMXX#200]
В amx 1.10 он вообще отключен, а в amx 1.9 он не срабатывает при некоторых условиях, например если создан файл cfg в amxmodx/configs/maps/

**Comment by 2020karaulov2020** [comment]
пишут что OnAutoConfigsBuffered должна быть хорошей альтернативой

**Comment by 2020karaulov2020** [comment]
Я так понял этот форвард должен срабатывать только при условии что для карты создан конфиг в /amxmodx/config/maps . А в 1.9 и ниже срабатывает в любом случае из-за ошибки в коде?

**Comment by wopox1337** [comment]
> В amx 1.10 он вообще отключен

Как ты это понял?

> в amx 1.9 он не срабатывает при некоторых условиях, например если создан файл cfg в amxmodx/configs/maps/

<img width="1349" alt="Снимок экрана 2021-06-05 в 13 04 28" src="https://user-images.githubusercontent.com/18553678/120888011-bf7df480-c5fe-11eb-9091-5ba3fc0b8cb5.png">

Не подтверждаю. Всё в порядке, работает как и ожидается.


> в 1.9 срабатывает в любом случае из-за ошибки в коде AMXMODX

Ты не правильно понял принцип работы. Рекомендую ознакомиться с документацией AMXMODX.

**Comment by 2020karaulov2020** [comment]
ну в общем последняя версия стоит со всеми модулями, не вызывается этот форвард
в 1.9 работает нормально если не создавать конфиги в amxmodx/config/maps папке

**Comment by wopox1337** [comment]
Судя по всему твои проблемы не имеют отношения к данному репозиторию, но спасибо за бдительность. 🙂

**Comment by 2020karaulov2020** [comment]
@wopox1337 ладно ваще насрать но если что проблема не только у меня

**Comment by wopox1337** [comment]
@2020karaulov2020 в чём собственно проблема? Конкретно, что не так у тебя с ChatAdditions?

**Comment by 2020karaulov2020** [comment]
@wopox1337 да форвард этот проклятый)
![Screenshot_20210605-211306](https://user-images.githubusercontent.com/62130676/120901625-c7608780-c644-11eb-8fd7-015883133a6c.png)
![Screenshot_20210605-211218](https://user-images.githubusercontent.com/62130676/120901631-d0515900-c644-11eb-8652-625b0d4e6e55.png)
https://github.com/alliedmodders/amxmodx/issues/728

**Comment by 2020karaulov2020** [comment]
@wopox1337 https://github.com/alliedmodders/amxmodx/issues/728 в общем форвард живет своей жизнью и может сломаться от неизвестно чего.
