### ISSUE TITLE
`ca_log_type 0` creates folder `ChatAdditions/` but logs to common file

### ISSUE THREAD

**Issue by wopox1337** [ChatAdditions/ChatAdditions_AMXX#207]
<img width="629" alt="Снимок экрана 2021-07-16 в 00 30 27" src="https://user-images.githubusercontent.com/18553678/125860363-2767501e-e6d7-456c-949d-550f493b65af.png">

**Comment by Nord1cWarr1or** [comment]
@wopox1337 Это вряд-ли можно назвать багом. 

1) Если человек захочет включить логи "на лету", создастся ли папка?
2) Если человек наоборот, выключить логи "на лету", папка явно не удалится.
