### ISSUE TITLE
adminchat.amxx

### ISSUE THREAD

**Issue by g2rise** [ChatAdditions/ChatAdditions_AMXX#237]
(Админ) 11 :  админа рот е*ал

после гага игрок может отправлять сообщения в админ чат, нужно поправить

**Comment by wopox1337** [comment]
Необходимо переместить `adminchat.amxx` ниже, чем `ChatAdditions` плагины.
https://github.com/ChatAdditions/ChatAdditions_AMXX/blob/78bf5372c79111ce5d2256a58cc925659710e411/cstrike/addons/amxmodx/configs/plugins-ChatAdditions.ini#L19
