### ISSUE TITLE
`OnConfigsExecuted()` is broken in AMXX

### ISSUE THREAD

**Issue by UnrealKaraulov** [ChatAdditions/ChatAdditions_AMXX#238]
@wopox1337  Введи в plugin_precache или в plugin_init команду server_cmd("add_amxx.cfg") 

Команда не так важна,, главное что бы в команде присутствовала строка **amxx.cfg** , и OnConfigsExecuted  никогда не вызовется.

**Comment by UnrealKaraulov** [comment]
Думаю сломано в версии 1.9 и 1.10

**Comment by UnrealKaraulov** [comment]
![image](https://user-images.githubusercontent.com/88730285/144562637-14213b8c-0ff1-4d3e-b40b-3f661580973c.png)
Хотя кому я это говорю он же сам лайкнул пост с этой ошибкой))

Любой админ менеджер и бан менеджер выполняет amxx.cfg при запуске, и после чего ChatAdditions ломается)

**Comment by wopox1337** [comment]
ты ничего не перепутал?

> команду **server_cmd("add_amxx.cfg")**

**Comment by wopox1337** [comment]
не подтверждаю.
![image](https://user-images.githubusercontent.com/18553678/144564187-96dfd7e2-f41a-4faf-a5ed-77756f1e928c.png)


Как ещё убедиться, в том, что ты описал правильный путь к воспроизведению ошибки?

**Comment by UnrealKaraulov** [comment]
@wopox1337 версия amxmodx выше 2015 года?

**Comment by wopox1337** [comment]
```
> version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.11.0.767-dev
Build date: 03:13:55 Oct 25 2021 (2753)
Build from: https://github.com/dreamstalker/rehlds/commit/471158b

> game version
ReGameDLL version: 5.21.0.540-dev
Build date: 17:33:16 Oct 25 2021
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/b9cccc6

> meta version
Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:54 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70

> meta list
Currently loaded plugins:
      description  stat pend  file                 vers             src  load  unload
 [ 1] AMX Mod X    RUN   -    amxmodx_mm_i386.so   v1.10.0.5412     ini  Start ANY
 [ 2] Reunion      RUN   -    reunion_mm_i386.so   v0.1.0.92        ini  Start Never
 [ 3] ReAPI        RUN   -    reapi_amxx_i386.so   v5.21.0.248-dev  pl1  ANY   Never
 [ 4] MySQL        RUN   -    mysql_amxx_i386.so   v1.10.0.5412     pl1  ANY   ANY
 [ 5] SQLite       RUN   -    sqlite_amxx_i386.so  v1.10.0.5412     pl1  ANY   ANY
5 plugins, 5 running

> amxx modules
Currently loaded modules:
      name                    version     author               status
 [ 1] ReAPI                   5.21.0.248  Asmodai & s1lent     running
 [ 2] MySQL                   1.10.0.541  AMX Mod X Dev Team   running
 [ 3] SQLite                  1.10.0.541  AMX Mod X Dev Team   running
3 modules, 3 correct

> amxx version
AMX Mod X 1.10.0.5412 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Dec  6 2020 12:11:05
Built from: https://github.com/alliedmodders/amxmodx/commit/a4e929e
Build ID: 5412:a4e929e
Core mode: JIT+ASM32
```

**Comment by UnrealKaraulov** [comment]
@wopox1337  Возможно требуется полный путь к amxx.cfg с выполнением, а не частичное совпадение, хотя судя по коду именно частичное ищет.

**Comment by UnrealKaraulov** [comment]
Написано что только в таком случае блокируется

![image](https://user-images.githubusercontent.com/88730285/144566320-79ed4a40-c828-4117-84cf-5b7e1a927c00.png)
https://github.com/alliedmodders/amxmodx/issues/728#issue-450682936

**Comment by wopox1337** [comment]
@UnrealKaraulov благодарю за бдительность! Исправлено в [релизе v1.8.1](https://github.com/ChatAdditions/ChatAdditions_AMXX/releases/tag/v1.8.1)

**Comment by UnrealKaraulov** [comment]
Thanks! I tried to fix it in this pull request : https://github.com/alliedmodders/amxmodx/pull/1022
