### ISSUE TITLE
Offline gag

### ISSUE THREAD

**Issue by TheKrytyk** [ChatAdditions/ChatAdditions_AMXX#247]
Hello, I would like to ask you to add an option to gag players who left the server.

**Comment by wopox1337** [comment]
@TheKrytyk This is possible with the command `amx_gag`.

**Comment by TheKrytyk** [comment]
Nope. "Offline ban":

```
amx_gag kentucky "Provocations" 10080
Can't find player by arg=`kentucky`
```
